In [5]:
# function so that the columns of the output matrix are powers of the input vector
import numpy as np
x = np.array([1,2,3,4,5])
N = 5
x

array([1, 2, 3, 4, 5])

In [6]:
[x**(N-i-1) for i in range(N)]

[array([  1,  16,  81, 256, 625], dtype=int32),
 array([  1,   8,  27,  64, 125], dtype=int32),
 array([ 1,  4,  9, 16, 25], dtype=int32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([1, 1, 1, 1, 1], dtype=int32)]

In [9]:
np.column_stack([x**(N-i-1) for i in range(N)])

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [41]:
# function to find moving average in an array over a window

def moving_average(m, wind):
    l =[]
    counter = 0
    start = 0
    for j in range(0,(len(m)-wind+1)):
        summation = 0
        for i in m[start:start+wind]:
            summation = summation + i
        l.append(float(summation/3))
        start += 1
    return np.array(l)

In [42]:
my_nos = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [43]:
moving_average(my_nos,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])